version: '3'
services:
  model:
    devices: 
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    build: .
    container_name: face_mask_detect_model 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]